service: ruby-pg-layers
provider:
  name: aws

layers:
  pgRuby25:
    path: layer
    description: A Layer to fix postgres support in Ruby 2.5 Lambda functions
    compatibleRuntimes:
      - ruby2.5